### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Bakaika** [Bakaika/todo#1]
- [ ] rust shell (replace ysh + oh-my-zsh (theme=refined) + fast-syntax-highlighting) (rsh)?
- [ ] rust package manager similar to Alpine Linux's `apk` but builds everything you install, basically cargo (rpk)?
- [ ] rust editor like `micro` WITH AUTOCOMPLETE!!!! (ri)?
- [ ] rust jvm (rava)?
- [ ] install cargo-apk (`openssl` dep is old, update)
- [ ] rust-only openssl impl (rssl)?
- [ ] rust-only git/subversion impl (rit)?
- [ ] make rust-based linux-like distro/android app (rinx)?
